openapi: 3.0.0
info:
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)
    or HTML.
  title: Swagger test
  version: 0.1.9
servers:
- url: /
paths:
  /api/bin/{uuid}:
    get:
      description: Optional extended description in CommonMark or HTML.
      parameters:
      - description: The uuid of the data-key
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          format: uuid4
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: A JSON array of user names
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
          description: A JSON array with error description and status code
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
          description: A JSON array of user names
      summary: Returns decoded data by uuid key.
      x-accepts: application/json
    put:
      description: Optional extended description in CommonMark or HTML.
      parameters:
      - description: The uuid of the data-key
        explode: false
        in: path
        name: uuid
        required: true
        schema:
          format: uuid4
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                value:
                  example: some value to be encoded
                  type: string
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Updating existing record in db
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_201'
          description: Creating record in db from json data and returns response with
            data and status code
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400_1'
          description: A response with error message and status code. Returns one
            value from given example.
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404_1'
          description: A response with error message and status code
      summary: Accepts data and store it in binary format
      x-contentType: application/json
      x-accepts: application/json
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
  schemas:
    inline_response_404:
      properties:
        error:
          example: no uuid-key was found
          type: string
        status:
          example: "404"
          type: string
      type: object
    inline_response_404_1:
      properties:
        uuid:
          $ref: '#/components/schemas/inline_response_404'
      type: object
    inline_response_200_1:
      example:
        value: some value which was updated
        timestamp: "1673425999.603392"
        status: "200"
      properties:
        value:
          example: some value which was updated
          type: string
        timestamp:
          example: "1673425999.603392"
          type: string
        status:
          example: "200"
          type: string
      type: object
    inline_response_201:
      properties:
        value:
          example: some value which was encoded to binary format
          type: string
        timestamp:
          example: "1673425999.603392"
          type: string
        status:
          example: "201"
          type: string
      type: object
    inline_response_200:
      example:
        value: some value decoded from binary format
        timestamp: "1673425999.603392"
        status: "200"
      properties:
        value:
          example: some value decoded from binary format
          type: string
        timestamp:
          example: "1673425999.603392"
          type: string
        status:
          example: "200"
          type: string
      type: object
    inline_object:
      properties:
        value:
          example: some value to be encoded
          type: string
      type: object
    inline_response_400:
      properties:
        error:
          example: given uuid-key is not in uuid format
          type: string
        status:
          example: "400"
          type: string
      type: object
    inline_response_400_1:
      properties:
        error:
          description: returns one of given in example values
          example: no uuid-key was found OR given uuid-key is not in uuid format
          type: string
        status:
          example: "400"
          type: string
      type: object

